SE-98: fix export with `--dashboard` flag
percona/pmm-dump pull request #147
Opened 2024-05-31 01:18 UTC by pooknull

https://perconadev.atlassian.net/browse/SE-98

2024-06-05 20:50 UTC, svetasmirnova requested changes
I am still getting error with the dashboard, attached to the bug report.

```
$ ./pmm-dump export --pmm-url='https://admin:svetasveta@172.17.0.3'  --allow-insecure-certs --dashboard='Percona - DB Cluster'
2024-06-05T23:49:28+03:00 INF Credential user was obtained from pmm-url
2024-06-05T23:49:28+03:00 INF Credential password was obtained from pmm-url
2024-06-05T23:49:28+03:00 FTL Error retrieving dashboard selectors: get selectors from dashboard: get selectors: parse templating vars: to prometheus var: not supported type by pmm-dump: constant

$ ./pmm-dump version
Version: v0.7.0-ga, Build: 7b4681f
```

2024-06-18 13:22 UTC, svetasmirnova commented
Now I get:

```
$ ./pmm-dump export --pmm-url='https://admin:svetasveta@172.17.0.2'  --allow-insecure-certs --dashboard='Percona - DB Cluster'
2024-06-18T16:20:41+03:00 INF Credential user was obtained from pmm-url
2024-06-18T16:20:41+03:00 INF Credential password was obtained from pmm-url
2024-06-18T16:20:41+03:00 FTL Error retrieving dashboard selectors: get selectors from dashboard: get selectors: parse templating vars: parse templating var: parse templating query: interpolate query: failed to interpolate query
sveta@s76:~/src/percona/pmm-dump$ ./pmm-dump version
Version: v0.7.0-ga, Build: a486ff5

```

2024-06-18 22:33 UTC, svetasmirnova reviewed
pmm-dump now completes succesfully for the test dashboard. I still recommend adding a test for this case to avoid regressions in the future.

2024-06-21 13:35 UTC, artemgavrilov approved these changes

2024-06-21 13:35 UTC, artemgavrilov commented on pkg/grafana/expr/vmquery.go
> +				}
We can omit `else` here
```suggestion
				}
				
				s += f.Label
				switch {
				case f.IsNegative && f.IsRegexp:
					s += "!~"
				case f.IsNegative && !f.IsRegexp:
					s += "!="
				case !f.IsNegative && f.IsRegexp:
					s += "=~"
				case !f.IsNegative && !f.IsRegexp:
					s += "="
				}
				s += fmt.Sprintf(`"%s"`, f.Value)
				
```

2024-07-17 12:32 UTC, svetasmirnova approved these changes

2024-07-17 12:33 UTC, merged